- hosts: test
  become: true
  tasks:
    - name: install httpd
      package:
        name: httpd
        state: present
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: true  